### ISSUE TITLE
Possible to query different versions of taxref with the rtaxref package ?

### ISSUE THREAD

**Issue by PascalIrz** [Rekyt/rtaxref#21]
Bonjour,
Merci pour votre développement de package qui répond forcément à des besoins.
Sur [la page de l'API](https://taxref.mnhn.fr/taxref-web/api/doc) je lis "Cette API diffuse les informations du référentiel national TAXREF (de la version 2.0 à la version 15.0) et de la Base de connaissance associée à la version 15.0.". Est-il possible d'interroger une version spécifique de Taxref avec les fonctions du package {rtaxref} ?
Merci d'avance.

**Comment by Rekyt** [comment]
Bonjour @PascalIrz,
Merci beaucoup de votre intérêt ! En effet TAXREF rend possible l'interrogation de toutes les versions de TAXREF (ce qui est
très utile).

La plupart des fonctions qui proposent une requête via un identifiant de TAXREF (par ex. `rt_taxa_children()`) répondent pour toutes les versions de TAXREF. Ces requêtes renvoient une colonne `taxrefVersion` qui permet de connaître la version la plus récente (et l'historique) du taxon en question.

D'autres fonctions permettent l'interrogation d'une version de TAXREF spécifique (`rt_taxa_search()` et une extension de `rt_operational_groups()` pas encore disponible). Malheureusement, pour l'instant, je n'ai pas implémenté cette possibilité dans `rtaxref`, ce ne devrait pas être trop compliqué à faire dans la mesure où il suffit d'ajouter un argument `version` à la requête.

Je n'aurais pas le temps de l'implémenter tout de suite, donc si jamais vous souhaitez le faire, je suis évidemment ouvert à des pulls request :)

**Comment by Rekyt** [comment]
Je rajoute qu'avec `rt_taxref_history()` vous pouvez obtenir l'historique des noms de taxons dans les différentes versions de TAXREF.

**Comment by PascalIrz** [comment]
Merci pour cette réponse rapide !
Je vais jeter un oeil sur le code et s'il y a matière à PR je fais ça.

**Comment by Rekyt** [comment]
`rt_taxa_search()`  dispose maintenant d'un argument `version` qui permet d'interroger spécifiquement les différentes versions de TAXREF!
Il faut que l'argument soit de la forme "2.0", "3.0", etc.

Je rappelle que le package est pour l'instant loin de la stabilité parce qu'il n'effectue aucun vérification _a priori_ des arguments.

Et je suis toujours preneur de retours/suggestions/bugs pour l'améliorer.
